apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
spec:
 ### ADD IF ENV=LOCAL > TYPE:NODEPORT ELSE > 
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: {{ .Release.Name }}

